name: Build and Deploy LaTeX to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'latex/**.tex'
      - 'styles/**'
      - 'vercel.json'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install Dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

      # Step 3: Convert LaTeX to HTML
      - name: Convert LaTeX to HTML
        run: |
          mkdir -p public
          # Convert LaTeX files to HTML
          for texfile in $(find latex -name "*.tex"); do
            relative_path=${texfile#latex/}
            output_path=${relative_path%.tex}.html
            # Handle the main.tex as index.html
            if [[ "$relative_path" == "main.tex" ]]; then
              output_path="index.html"
            fi
            mkdir -p public/$(dirname "$output_path")
            pandoc "$texfile" \
              --standalone \
              --toc \
              --mathjax \
              --css styles/styles.css \
              -o "public/${output_path}"
          done
          # Copy all non-tex files (assets) to public/
          rsync -av --exclude='*.tex' latex/ public/

      # Step 4: Replace .tex links with clean URLs
      - name: Update HTML Links
        run: |
          find public -name "*.html" -exec sed -i 's/\.tex//g' {} +

      # Step 5: List Public Directory Contents (Debugging)
      - name: List Public Directory Contents
        run: |
          echo "Contents of public/:"
          ls -R public/

      # Step 6: Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: public
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

